[package]
name = "omniqueue"
version = "0.1.0"
license = "MIT"
description = "An abstraction layer over various queue backends"
authors = ["Svix Inc. <oss@svix.com>"]
repository = "https://github.com/svix/omniqueue-rs/"
readme = "../README.md"

edition = "2021"

[dependencies]
async-trait = "0.1"
aws-config = { version = "0.55", optional = true }
aws-sdk-sqs = { version = "0.25", optional = true }
bb8 = { version = "0.8", optional = true }
bb8-redis = { version = "0.13", optional = true }
futures-util = { version = "0.3.28", default-features = false, features = ["async-await", "std"], optional = true }
google-cloud-googleapis = { version = "0.12.0", optional = true }
google-cloud-pubsub = { version = "0.22.1", optional = true }
lapin = { version = "2", optional = true }
redis = { version = "0.23", features = ["tokio-comp", "tokio-native-tls-comp", "streams"], optional = true }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
svix-ksuid = { version = "0.7.0", optional = true }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", optional = true }
tracing = "0.1"

[dev-dependencies]
fastrand = "1.9"
tokio-executor-trait = "2.1"
tokio-reactor-trait = "1.1"

[features]
default = ["memory_queue", "gcp_pubsub", "rabbitmq", "redis", "redis_cluster", "sqs"]
gcp_pubsub = [
    "dep:futures-util",
    "dep:google-cloud-googleapis",
    "dep:google-cloud-pubsub",
    "dep:tokio-util",
]
memory_queue = []
rabbitmq = ["dep:futures-util", "dep:lapin"]
redis = ["dep:bb8", "dep:bb8-redis", "dep:redis", "dep:svix-ksuid"]
redis_cluster = ["redis", "redis/cluster-async"]
sqs = ["dep:aws-config", "dep:aws-sdk-sqs"]
